[build]
   command = "CI=false npm run build"  # Ensure you are using the build script that skips or fixes ESLint warnings
  publish = "build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true
